# Generated by Django 4.1.5 on 2023-02-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yor_name', models.CharField(max_length=255)),
                ('yor_phn', models.CharField(max_length=10)),
                ('your_Email', models.EmailField(max_length=254)),
                ('subjects', models.CharField(max_length=255)),
                ('messsage', models.TextField()),
            ],
        ),
    ]
